apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  AIRFLOW__CORE__LOAD_EXAMPLES: "True"
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "10"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__WEBSERVER__AUTHENTICATE: "False"
  AIRFLOW__LOGGING__LOGGING_LEVEL: "DEBUG"