apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: airflow
namespace: airflow

resources:
  - namespace.yaml
  - airflow-serviceaccount.yaml
  - airflow-configmap.yaml
  - pod-template-configmap.yaml
  - redis-deployment.yaml
  - persistent-volumes.yaml
  - postgresql-setup.yaml
  - airflow-init-job.yaml
  - airflow-apiserver.yaml
  - airflow-scheduler.yaml
  - airflow-dag-processor.yaml
  - airflow-triggerer.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/name: airflow
  app.kubernetes.io/version: "3.1.0"
  app.kubernetes.io/component: airflow
  app.kubernetes.io/part-of: airflow

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - target:
      kind: Namespace
      name: airflow
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-3"
  - target:
      kind: Job
      name: postgresql-airflow-setup
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: Job
      name: airflow-init
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-1"
  - target:
      kind: Secret
      name: pg-superuser
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: ServiceAccount
      name: airflow
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: PersistentVolumeClaim
      name: airflow-dags-pvc
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: PersistentVolumeClaim
      name: airflow-logs-pvc
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: PersistentVolumeClaim
      name: airflow-plugins-pvc
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: Secret
      name: airflow-fernet-key
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: Secret
      name: airflow-webserver-secret
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: Secret
      name: airflow-api-secrets
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: ConfigMap
      name: airflow-config
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"
  - target:
      kind: ConfigMap
      name: pod-template-configmap
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-2"