apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
  AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
  AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"