apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: airflow-base

namespace: airflow

resources:
  - airflow.yaml

commonLabels:
  app.kubernetes.io/name: airflow
  app.kubernetes.io/component: workflow-orchestration
  app.kubernetes.io/part-of: airflow

commonAnnotations:
  maintained-by: "DevOps Team"